version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root!@#
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

volumes:
  mysql:

# docker-compose -f 01.mysql-stack.yml up

# docker exec -it db1 mysql -uroot -p